# Generated by Django 4.1.1 on 2022-10-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0003_rename_apellido_clientes_marca_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Pedidos',
        ),
    ]
