# Generated by Django 4.1.1 on 2022-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
