# Generated by Django 4.1.1 on 2022-10-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0005_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
